### ISSUE TITLE
Simon Shirt Issue

### ISSUE THREAD

**Issue by tayduffers** [freesewing/freesewing.org#417]
When choosing a model for the Simon pattern, I receive the following page instead of a pattern. I tried with a couple other patterns but it just seems to be this one that causes any issue: 

![github](https://user-images.githubusercontent.com/58922494/70873227-c59b9380-1f7a-11ea-9032-edd352f728ee.JPG)

**Comment by joostdecock** [comment]
Thanks for reporting this. This is a dupe of #416 so I will close this one and track the process there.
You can subscribe to #416 to receive updated.

**Comment by joostdecock** [comment]
This has been fixed :)

**Comment by tayduffers** [comment]
> This has been fixed :)

I just tried it again this morning and I'm still receiving the same error 😔. Any thoughts?

**Comment by joostdecock** [comment]
Can you do a hard reload (ctrl-shift reload) to make sure your browser is not using any cached code.

**Comment by joostdecock** [comment]
Did you have a chance to try this?
